#!/usr/bin/env bash

# Copyright 2017, Z Lab Corporation. All rights reserved.
# Copyright 2017, Kubernetes scripts contributors
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

set -e

if [[ $# != 2 ]]; then
  echo "Usage: $0 PERIOD INTERVAL" >&2
  echo "" >&2
  echo "This script waits for all pods to be running in the current namespace." >&2

  exit 1
fi

period="$1"
interval="$2"

for ((i=0; i<$period; i+=$interval)); do
  pods="$(kubectl get po -o 'jsonpath={range .items[?(@.status.phase!="Running")]}{"\n"}{.metadata.name}{end}')"
  if [[ "$(echo -n "$pods" | wc -l)" > 0 ]]; then
    echo "Waiting for pods to be running..."
  else
    exit 0
  fi

  sleep "$interval"
done

echo "After waiting for $period seconds, all pods are not running yet."
exit 2
# vim: ft=sh :
